In [1]:
import torch

In [22]:
x = torch.randn((2, 2), requires_grad=True)

In [31]:
x

tensor([[ 1.2826,  0.6443],
        [-1.1700,  0.4183]], requires_grad=True)

In [34]:
x.requires_grad_(False)

tensor([[ 1.2826,  0.6443],
        [-1.1700,  0.4183]])

In [38]:
x.detach_()

tensor([[ 1.2826,  0.6443],
        [-1.1700,  0.4183]])

In [39]:
with torch.no_grad():
    pass

In [45]:
weights = torch.ones(2, requires_grad=True)

In [47]:
for epoch in range(10):
    y = (weights * 2).sum()
    y.backward()
    print(weights.grad)

tensor([22., 22.])
tensor([24., 24.])
tensor([26., 26.])
tensor([28., 28.])
tensor([30., 30.])
tensor([32., 32.])
tensor([34., 34.])
tensor([36., 36.])
tensor([38., 38.])
tensor([40., 40.])
