In [21]:
import torch
import torch.nn as nn

In [41]:
X = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)
X = torch.reshape(X, (-1, 1))
Y = X * 2

In [42]:
X, Y

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.]]),
 tensor([[ 2.],
         [ 4.],
         [ 6.],
         [ 8.],
         [10.]]))

In [43]:
#W = torch.tensor(0.1, requires_grad=True)
model = nn.Linear(X.shape[1], X.shape[1])

In [44]:
loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [46]:
epochs = 1000
for i in range(epochs):
    Y_pred = model(X)
    _loss = loss(Y, Y_pred)
    _loss.backward()
    optimizer.step()
    optimizer.zero_grad()
    if i % 100 == 0:
        print(f'---- loss  ---------- {_loss:.8f}', model.parameters())

---- loss  ---------- 0.00000200 <generator object Module.parameters at 0x7fb38a3ae2e0>
---- loss  ---------- 0.00000102 <generator object Module.parameters at 0x7fb38a3ae270>
---- loss  ---------- 0.00000052 <generator object Module.parameters at 0x7fb38a3ae270>
---- loss  ---------- 0.00000026 <generator object Module.parameters at 0x7fb38a3ae270>
---- loss  ---------- 0.00000013 <generator object Module.parameters at 0x7fb38a3ae270>
---- loss  ---------- 0.00000007 <generator object Module.parameters at 0x7fb38a3ae270>
---- loss  ---------- 0.00000003 <generator object Module.parameters at 0x7fb38a3ae270>
---- loss  ---------- 0.00000002 <generator object Module.parameters at 0x7fb38a3ae270>
---- loss  ---------- 0.00000001 <generator object Module.parameters at 0x7fb38a3ae270>
---- loss  ---------- 0.00000000 <generator object Module.parameters at 0x7fb38a3ae270>


In [48]:
model(torch.tensor([10], dtype=torch.float32))

tensor([20.0002], grad_fn=<AddBackward0>)