In [40]:
import torch
import numpy as np

In [29]:
x = torch.randn(2, 3)
y = torch.randn(2, 3)

In [34]:
x.add(y)

tensor([[ 1.5142, -0.9629, -2.2584],
        [ 2.5373,  0.9071,  0.7562]])

In [39]:
a = torch.randn(4, 4)
a.view(-1, 8)

tensor([[ 1.2122, -1.0638, -1.3330,  1.4265,  1.0456,  0.4695,  0.2255,  0.2234],
        [ 1.9557, -0.1659, -1.5815,  0.3741,  0.6834, -0.5570,  0.3464, -0.2508]])

In [45]:
b = np.random.randn(2, 2)
torch.from_numpy(b)

tensor([[-0.8680, -0.0522],
        [ 0.5379,  0.0196]], dtype=torch.float64)

In [47]:
torch.cuda.is_available()

False

In [49]:
torch.ones(2,2,requires_grad=True)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)